// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXWioFH2Z3_EXsf0DaIEp0tRkYKUQDLw',
    appId: '1:77214966077:web:1a7dabc87056bdb27fe554',
    messagingSenderId: '77214966077',
    projectId: 'login-cfpluscafee',
    authDomain: 'login-cfpluscafee.firebaseapp.com',
    databaseURL: 'https://login-cfpluscafee-default-rtdb.firebaseio.com',
    storageBucket: 'login-cfpluscafee.firebasestorage.app',
    measurementId: 'G-DFLNFFMRCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1jf2f8HHsbT0bVscCEU7DJhuV1aqDLk',
    appId: '1:77214966077:android:97ac8538e82fb5dd7fe554',
    messagingSenderId: '77214966077',
    projectId: 'login-cfpluscafee',
    databaseURL: 'https://login-cfpluscafee-default-rtdb.firebaseio.com',
    storageBucket: 'login-cfpluscafee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrORqXwdlU4HFmxfBqtNb0OLInYZDSRpU',
    appId: '1:77214966077:ios:ee93d8c303984f507fe554',
    messagingSenderId: '77214966077',
    projectId: 'login-cfpluscafee',
    databaseURL: 'https://login-cfpluscafee-default-rtdb.firebaseio.com',
    storageBucket: 'login-cfpluscafee.firebasestorage.app',
    iosBundleId: 'com.example.appcafeUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrORqXwdlU4HFmxfBqtNb0OLInYZDSRpU',
    appId: '1:77214966077:ios:ee93d8c303984f507fe554',
    messagingSenderId: '77214966077',
    projectId: 'login-cfpluscafee',
    databaseURL: 'https://login-cfpluscafee-default-rtdb.firebaseio.com',
    storageBucket: 'login-cfpluscafee.firebasestorage.app',
    iosBundleId: 'com.example.appcafeUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyXWioFH2Z3_EXsf0DaIEp0tRkYKUQDLw',
    appId: '1:77214966077:web:356d24347352b6487fe554',
    messagingSenderId: '77214966077',
    projectId: 'login-cfpluscafee',
    authDomain: 'login-cfpluscafee.firebaseapp.com',
    databaseURL: 'https://login-cfpluscafee-default-rtdb.firebaseio.com',
    storageBucket: 'login-cfpluscafee.firebasestorage.app',
    measurementId: 'G-4PB2GEJBK3',
  );
}
